name: 'GitHub Copilot Chargeback'
description: 'Sync GitHub organization or team members with GitHub Cost Centers for Copilot billing management'
author: 'ewega'

# Define your inputs here.
inputs:
  github_organization:
    description: 'GitHub organization name'
    required: true
  github_team:
    description: 'GitHub team name (optional)'
    required: false
  github_cost_center_name:
    description: 'GitHub Cost Center Name'
    required: true

# Define your outputs here.
outputs:
  result:
    description: 'Result of the action'

runs:
  using: node20
  main: dist/index.js
