name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  github_team:
    description:
      'GitHub team name (optional - if provided, only sync users from this team)'
    required: false
  github_cost_center_name:
    description: 'GitHub Cost Center Name'
    required: true
  github_enterprise:
    description: 'GitHub Enterprise slug'
    required: true
  github_token:
    description: 'GitHub Personal Access Token with appropriate permissions'
    required: true

# Define your outputs here.
outputs:
  result:
    description: 'Result of the action'

runs:
  using: node20
  main: dist/index.js
