name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action (Dry Run)
        id: test-action
        uses: ./
        with:
          github_organization: 'test-org'
          github_team: 'test-team'
          github_cost_center_name: 'test-cost-center'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Print Output
        id: output
        run: |
          echo "Action completed with result: ${{ steps.test-action.outputs.result }}"
          echo "This is expected to fail in CI as it makes real API calls to Cost Center API"

      - name: Validate Action Structure
        id: validate
        run: |
          echo "Validating action structure..."
          if [ -f "action.yml" ]; then
            echo "✓ action.yml exists"
          else
            echo "✗ action.yml missing"
            exit 1
          fi

          if [ -f "dist/index.js" ]; then
            echo "✓ dist/index.js exists"
          else
            echo "✗ dist/index.js missing"
            exit 1
          fi

          echo "Action structure validation complete"
